web_scraping/__init__.py
from flask import Flask


def create_app():
    app = Flask(__name__)

    from web_scraping.main.routes import main
    app.register_blueprint(main)

    return app

web_scraping/main/routes.py
from flask import render_template, request, Blueprint
from web_scraping.main.searching import morele_net, x_kom, komputronik
from web_scraping.main.functions import get_product
from statistics import median_low

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home", methods=['GET', 'POST'])
def home():
    if request.method == 'POST':
        user_input = request.form['product']
        phrase = user_input.split(' ')

        morele_products = morele_net(phrase)
        x_kom_products = x_kom(phrase)
        komputronik_products = komputronik(phrase)

        products = morele_products + x_kom_products + komputronik_products
        sorted_list = sorted(products, key=lambda i: i['item_price'])
        best_value = sorted_list[0]
        medium_price = median_low(i['item_price'] for i in sorted_list)
        medium_value = get_product(medium_price, sorted_list)
        worst_value = sorted_list[-1]

        return render_template('results.html', title='Results', product1=best_value,
                               product2=medium_value, product3=worst_value)

    return render_template('home.html', title='Home')


@main.route("/about")
def about():
    return render_template('about.html', title='About')


@main.route("/contact")
def contact():
    return render_template('contact.html', title='About')


@main.route("/results")
def results():
    return render_template('results.html', title='Results')

templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
        <title>BuyMore - {{ title }}</title>
    {% else %}
        <title>BuyMore</title>
    {% endif %}
    <link rel="stylesheet" type="text/css" href="static/style.css">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap&subset=latin-ext" rel="stylesheet"
          type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap&subset=latin-ext" rel="stylesheet"
          type="text/css">
</head>
<body>
    <div id="page">
        <div id="logo">
            BayMore PayLess
        </div>
        <div id="menu">
            <div class="option" href="home">
                <a href="home">Home</a>
            </div>
            <div class="option">
                <a href="about">About</a>
            </div>
            <div class="option">
                <a href="contact">Contact</a>
            </div>
            <div style="clear:both;"></div>
        </div>
        <div id="partners">
            <div class="title">Our partners</div>
            <div class="img">
                <a href="https://www.morele.net/">
                    <img src="static/img/morele.png">
                </a>
            </div>
            <div class="img">
                <a href="https://www.x-kom.pl/">
                    <img src="static/img/x-kom.png">
                </a>
            </div>
            <div class="img">
                <a href="https://www.komputronik.pl/">
                    <img src="static/img/komputronik.png">
                </a>
            </div>
        </div>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
        <div id="footer">
            Stropczyk software &reg; Copywright &copy; 2020
        </div>
    </div>
</body>
</html>

web_scraping/templates/about.html
{% extends "layout.html" %}
{% block content %}
<span class="title2">About</span>
<div class="dotted-line"></div>
{% endblock content %}

web_scraping/templates/contact.html
{% extends "layout.html" %}
{% block content %}
<span class="title2">Contact</span>
<div class="dotted-line"></div>
{% endblock content %}

web_scraping/templates/home.html
{% extends "layout.html" %}
{% block content %}
<span class="title2">Home Page</span>
<div class="dotted-line"></div>
<form action="/home" method="post">
    <label for="product">Search for product:</label><br><br>
    <input type="text" id="product" name="product"><br><br>
    <input type="submit" name="submit" value="Submit">
</form>
{% endblock content %}

web_scraping/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
        <title>BuyMore - {{ title }}</title>
    {% else %}
        <title>BuyMore</title>
    {% endif %}
    <link rel="stylesheet" type="text/css" href="static/style.css">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap&subset=latin-ext" rel="stylesheet"
          type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap&subset=latin-ext" rel="stylesheet"
          type="text/css">
</head>
<body>
    <div id="page">
        <div id="logo">
            BuyMore PayLess
        </div>
        <div id="menu">
            <div class="option">
                <a href="{{ url_for('main.home') }}">Home</a>
            </div>
            <div class="option">
                <a href="{{ url_for('main.about') }}">About</a>
            </div>
            <div class="option">
                <a href="{{ url_for('main.contact') }}">Contact</a>
            </div>
            <div style="clear:both;"></div>
        </div>
        <div id="partners">
            <div class="title">Our partners</div>
            <div class="img">
                <a href="https://www.morele.net/">
                    <img src="static/img/morele.png">
                </a>
            </div>
            <div class="img">
                <a href="https://www.x-kom.pl/">
                    <img src="static/img/x-kom.png">
                </a>
            </div>
            <div class="img">
                <a href="https://www.komputronik.pl/">
                    <img src="static/img/komputronik.png">
                </a>
            </div>
        </div>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
        <div style="clear:both;"></div>
        <div id="footer">
            Stropczyk software &reg; Copywright &copy; 2020
        </div>
    </div>
</body>
</html>

web_scraping/templates/results.html
{% extends "layout.html" %}
{% block content %}
<span class="title2">Results</span>
<div class="dotted-line"></div>
<div class="title">Best value:</div>
<article>
    <p>
        <a href="{{ product1.link }}">
            <img class="product-image" src="{{ product1.item_image }}" height="150">
        </a>
        <br>
        <span>{{ product1.item_name }}</span>
        <br>
        <span>{{ product1.item_price }}</span>
    </p>
</article>
<div class="dotted-line"></div>
<div class="title">Medium value:</div>
<article>
    <p>
        <a href="{{ product2.link }}">
            <img class="product-image" src="{{ product2.item_image }}" height="150">
        </a>
        <br>
        <span>{{ product2.item_name }}</span>
        <br>
        <span>{{ product2.item_price }}</span>
    </p>
</article>
<div class="dotted-line"></div>
<div class="title">Worst value:</div>
<article>
    <p>
        <a href="{{ product3.link }}">
            <img class="product-image" src="{{ product3.item_image }}" height="150">
        </a>
        <br>
        <span>{{ product3.item_name }}</span>
        <br>
        <span>{{ product3.item_price }}</span>
    </p>
</article>
<div class="dotted-line"></div>
{% endblock content %}